### ISSUE TITLE
Software dependencies

### ISSUE THREAD

**Issue by andreas-wilm** [xuchang116/smCounter#1]
Hi there, in addition to some of the dependencies mentioned in the README, could you please also mention the required/tested versions for pysam, scipy and Bedtools?
Thanks, Andreas

**Comment by xuchang116** [comment]
Hi Andreas, 

Sorry for the delayed reply. Here are the version numbers:

pysam : 0.9.0
scipy : 1.0.0
bedtools : 2.25.0

We have recently released smCounter2, the upgraded version of smCounter. If you are interested, please check out smCounter2 at https://github.com/qiaseq/qiaseq-dna and the manuscript at https://www.biorxiv.org/content/early/2018/03/14/281659. 
 
Chang
