### ISSUE TITLE
LSM: Fewer than 2 strong MTs

### ISSUE THREAD

**Issue by Tato14** [xuchang116/smCounter#2]
Hi!

Thanks for the great tool! I am wirking with QIAseq DNA panels and I am working using smCounter. However, all the variants that I am detecting are tagged at least as LSM. I am not quite sure what does this mean and what could be the problem of the samples. Example code:

python smCounter.py    --outPrefix $i    --bamFile "${i%}"_sorted.bam    --bedTarget QIAseq_DNA_panel.CDHS-13593Z-900.roi.bed    --mtDepth 3612    --rpb 8.6    --nCPU 10    --minBQ 20    --minMQ 30    --hpLen 10    --mismatchThr 6.0    --mtDrop 0    --maxMT 0    --primerDist 2    --threshold 0    --refGenome hg19.fasta    --bedTandemRepeats simpleRepeat_hg19_smCounter.txt    --bedRepeatMaskerSubset rmsk_hg19_smCounter_filter.txt    --bedtoolsPath ..
/BEDTools/2.26.0/bin/    --runPath ./    --logFile $i

Any idea?
Thanks!

**Comment by xuchang116** [comment]
Sorry for the (perhaps too late) reply. Strong MTs are molecular tags with sufficient reads and high concordance among these reads. For example, if an MT (or UMI) has 10 reads, 6 being "A" and 4 being "C". By majority vote this MT indicates "A" but it's not a strong MT for "A". 

I hope my answer helps. I recommend you to use smCounter2 in the future for better performance.  https://github.com/qiaseq/qiaseq-dna
